import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import UnitCard from "../components/UnitCard";
import styles from "../styles/Home.module.css";
import { prepXML } from "../utils/xml2";

export default function Home() {
  const [selectedFile, setSelectedFile] = useState();
  const [isFilePicked, setIsFilePicked] = useState(false);
  const [forceJSON, setForceJSON] = useState();

  const changeHandler = (event) => {
    setSelectedFile(event.target.files[0]);

    // let blob = file.fileBlob;
    var reader = new FileReader();
    reader.addEventListener("loadend", function () {
      // console.log(reader.result); // will print out file content
      prepXML(reader.result, (data) => {
        setForceJSON(data);
        setIsFilePicked(true);
      });
    });
    reader.readAsText(event.target.files[0]);
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {/* <main className={styles.main}> */}
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div>
          <input
            type="file"
            name="file"
            accept=".ros"
            onChange={changeHandler}
          />
        </div>

        {isFilePicked ? (
          <>
            {/* <div>Filename: {selectedFile.name} </div>
            <div>there are {forceJSON[0].upgrades.length}</div>
            {/* <div>there are {forceJSON[0].models.length}</div> */}
            {/* <div>there are {forceJSON[0].units.length}</div> */}
            {/* <div>there are {JSON.stringify(forceJSON)}</div> */}
            {/* <div>
              wtf
              {forceJSON[0].upgrades.map((model, i) => {
                return <UnitCard model={model} key={i} />;
              })}
            </div> */}
            <div>
              there are {forceJSON[0].units.length}
              {forceJSON[0].units.map((model, i) => {
                return <UnitCard model={model} key={i} />;
              })}
              <div>----------------------</div>
              <div>----------------------</div>
              {/* {JSON.stringify(forceJSON[0], null, 2)} */}
              <div>----------------------</div>
            </div>
            {/* <div>
              wtf3
              {forceJSON[0].units.map((model, i) => {
                return <UnitCard model={model} key={i} />;
              })}
            </div> */}
            {/* <div>{JSON.stringify(forceJSON)}</div> */}
          </>
        ) : (
          <div>Choose a file to show details</div>
        )}

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
        {/* </main> */}
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
